In [5]:
import pandas as pd
from IPython.display import display, HTML

In [6]:
scenarios = [
        "ASP-POTASSCO",
        "BNSL-2016",
        "CPMP-2015",
        "CSP-2010",
        "CSP-MZN-2013",
        "CSP-Minizinc-Time-2016",
        "GLUHACK-2018",
        "MAXSAT12-PMS",
        "MAXSAT15-PMS-INDU",
        "QBF-2011",
        "SAT03-16_INDU",
        "SAT12-INDU",
        "SAT18-EXP",
    ]
for scenario in scenarios:
    print(scenario)
    try:
        df = pd.read_csv(
            f"/home/ni574034/asf/bench/results/results_{scenario}_per_instance.csv"
        )
    except FileNotFoundError:
        print(f"File for scenario {scenario} not found, skipping.")
        continue

    display(df.groupby(["scenario", "selector"]).mean(numeric_only=True))

ASP-POTASSCO

                                       fold  test_score
scenario     selector
ASP-POTASSCO MultiClassClassifier  5.503091  596.399873
             PairwiseClassifier    5.379710  514.555983
             PairwiseRegressor     7.505792  522.413071
             PerformanceModel      5.503091  525.600749
             SingleBestSolver      5.503091  882.731809
             VirtualBestSolver     5.503091  402.806417

BNSL-2016

                                    fold   test_score
scenario  selector
BNSL-2016 MultiClassClassifier  5.497031  2188.896794
          PairwiseClassifier    5.497031  1666.312112
          PairwiseRegressor     5.497031  1659.426980
          PerformanceModel      4.666667  1486.948107
          SingleBestSolver      7.330976  9773.280424
          VirtualBestSolver     5.497031   251.012349

CPMP-2015
File for scenario CPMP-2015 not found, skipping.
CSP-2010
File for scenario CSP-2010 not found, skipping.
CSP-MZN-2013

                                       fold   test_score
scenario     selector
CSP-MZN-2013 MultiClassClassifier  5.499138  4886.725834
             PerformanceModel      5.333333  4223.420934
             SingleBestSolver      5.221398  8790.399452
             VirtualBestSolver     5.499138  3863.529067

CSP-Minizinc-Time-2016

                                             fold  test_score
scenario               selector
CSP-Minizinc-Time-2016 MultiClassClassifier   5.5  3031.55764
                       PairwiseClassifier     5.5  2905.94609
                       PairwiseRegressor      5.5  2917.41041
                       PerformanceModel       5.5  3132.12173
                       SingleBestSolver       5.5  3612.42646
                       VirtualBestSolver      5.5  2062.26244

GLUHACK-2018
File for scenario GLUHACK-2018 not found, skipping.
MAXSAT12-PMS

                                    test_score
scenario     selector
MAXSAT12-PMS MultiClassClassifier  3624.567854
             PairwiseClassifier    3267.617009
             PairwiseRegressor     3346.354189
             PerformanceModel      3366.327158
             SingleBestSolver      5527.651749
             VirtualBestSolver     3127.451107
estSolver    456.6                         NaN

MAXSAT15-PMS-INDU
File for scenario MAXSAT15-PMS-INDU not found, skipping.
QBF-2011
File for scenario QBF-2011 not found, skipping.
SAT03-16_INDU

                                    fold    test_score
scenario      selector
SAT03-16_INDU MultiClassClassifier  5.50   9196.095049
              PerformanceModel      6.25   9333.205189
              SingleBestSolver      5.50  10419.990304
              VirtualBestSolver     5.50   7306.400540

SAT12-INDU

                                     fold   test_score
scenario   selector
DU         SingleBestSolver      3.000000   138.800000
SAT12-INDU MultiClassClassifier  5.502999  2739.845698
           PairwiseClassifier    5.558516  2570.845167
           PairwiseRegressor     6.014286  2565.676914
           PerformanceModel      6.713936  2750.430526
           SingleBestSolver      6.562195  3438.769951
           VirtualBestSolver     5.502999  2392.569597

SAT18-EXP

                                    fold    test_score
scenario  selector
SAT18-EXP MultiClassClassifier  5.529745  15548.670766
          PairwiseClassifier    5.529745  14631.117013
          PairwiseRegressor     5.529745  13825.444145
          PerformanceModel      5.529745  14882.285389
          SingleBestSolver      2.000000  20401.758858
          VirtualBestSolver     5.529745   9841.410588

                                    test_score
scenario     selector
MAXSAT12-PMS MultiClassClassifier  3624.567854
             PairwiseClassifier    3267.617009
             PairwiseRegressor     3346.354189
             PerformanceModel      3366.327158
             SingleBestSolver      5527.651749
             VirtualBestSolver     3127.451107
estSolver    456.6                         NaN