In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(
    "/home/ni574034/asf/bench/results/results_MAXSAT12-PMS_per_instance.csv"
)
df

,scenario,fold,selector,instance,test_score
0,MAXSAT12-PMS,3,SingleBestSolver,benchmarks/pms_crafted/frb/frb35-17-2.partial....,197.73
1,MAXSAT12-PMS,3,SingleBestSolver,benchmarks/pms_crafted/frb/frb35-17-4.partial....,124.39
2,MAXSAT12-PMS,3,SingleBestSolver,benchmarks/pms_crafted/frb/frb40-19-3.partial....,21000.00
3,MAXSAT12-PMS,3,SingleBestSolver,benchmarks/pms_crafted/job-shop/la04-567-0696....,5.12
4,MAXSAT12-PMS,3,SingleBestSolver,benchmarks/pms_crafted/maxclicque/random/max_c...,3.29
...,...,...,...,...,...
4903,MAXSAT12-PMS,1,PairwiseRegressor,benchmarks/pms_industrial/pbo-mqc/nlogencdr/15...,104.77
4904,MAXSAT12-PMS,1,PairwiseRegressor,benchmarks/pms_industrial/pbo-mqc/nlogencdr/15...,19.41
4905,MAXSAT12-PMS,1,PairwiseRegressor,benchmarks/pms_industrial/pbo-routing/normaliz...,0.23
4906,MAXSAT12-PMS,1,PairwiseRegressor,benchmarks/pms_industrial/pbo-routing/normaliz...,5.58
4907,MAXSAT12-PMS,1,PairwiseRegressor,benchmarks/pms_industrial/protein_ins/1knt_.2k...,5.19

In [7]:
df.groupby(["scenario", "selector"]).mean(numeric_only=True)

                                    test_score
scenario     selector
MAXSAT12-PMS MultiClassClassifier  3624.567854
             PairwiseClassifier    3267.617009
             PairwiseRegressor     3346.354189
             PerformanceModel      3366.327158
             SingleBestSolver      5527.651749
             VirtualBestSolver     3127.451107
estSolver    456.6                         NaN